#!/bin/bash

bash_dir=$(cd "$(dirname "$0")" && pwd)
project_dir="$(dirname "$(dirname "$bash_dir")")"
root_dir="$(dirname "$(dirname "$project_dir")")"
link_dir="$root_dir/HALF_LIFE_DIR"
link_secondary=NO_CLIENT_DLL_PRESENT
link_dir2="$root_dir/NO_CLIENT_DLL"

for file in "$project_dir/"*.hltas; do
	file="$(basename "$file")"

	link_path="$link_dir/$file"
	file_path="$project_dir/$file"

	if test -f "$link_path"; then
		rm "$link_path"
	fi
	ln "$file_path" "$link_path"
	
	if $link_secondary; then
		link_path="$link_dir2/$file"
		if test -f "$link_path"; then
			rm "$link_path"
		fi
		ln "$file_path" "$link_path"
	fi

done
